name: EntityEvolution
version: 1.0 #'${project.version}'
main: com.msicraft.entityevolution.EntityEvolution
api-version: 1.16
authors: [ msicraft ]
description: Entity Evolution Plugin
commands:
  entityevolution:
    description: Plugin command
    aliases: [evolution, ee]
    permission-message: You don't have permission
permissions:
  entityevolution.command:
    description: Allow commands
    default: op